name: Manual trigger tests

on:
  workflow_dispatch:
    branches:
     - development
     - master

jobs:
  tests:
    name: Run smoke test scenario
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Cache deps
        uses: actions/cache@v3
        with:
         path: ~/.npm
         key: node-modules-${{ hashfiles('**/package-lock.json') }}
      - uses: actions/setup-node@v3
      - name: Install dependencies
        run: npm ci
      - name: Install playwright browsers
        run: npx playwright install --with-deps
      - name: Run tests
        run: npm run autotest
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30  